"""Fix contacts  unique constraints

Revision ID: 7a9dd5ea403f
Revises: b8e47361c5b6
Create Date: 2025-11-27 15:12:02.706589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9dd5ea403f'
down_revision: Union[str, Sequence[str], None] = 'b8e47361c5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_phone_number_key'), 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_unique_constraint(None, 'contacts', ['email', 'user_id'])
    op.create_unique_constraint(None, 'contacts', ['phone_number', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_unique_constraint(op.f('contacts_phone_number_key'), 'contacts', ['phone_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
